version: '2' # specify docker-compose version

# Define the services/containers to be run
services:

  mongodb: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding

  grobid: # 
    image: lfoppiano/grobid:0.4.1
    ports:
      - "9090:8080" # specify port forewarding

  preprocessing: # name of the third service
    build: preprocessing  # specify image to build container from
    tty: true
    stdin_open: true
    ports:
      - "7070:80" # specify port forewarding
    links:
      - grobid
      - express
#      - elasticsearch
    volumes:
      - /home/jachermocilla/Sources/PCLSearch/preprocessing:/opt/dev
  
  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    volumes:
      - /home/jachermocilla/Sources/mean-docker/express-server:/opt/dev
    links:
      - mongodb

  angular: # name of the first service
    build: angular-client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - /home/jachermocilla/Sources/mean-docker/angular-client:/opt/dev
  
#  elasticsearch: # name of the first service
#    build: elasticsearch # specify the directory of the Dockerfile
#    ports:
#      - "9200:9200" # specify port forewarding

